.TH "tests.unit.test_analyze" 3 "Sat Feb 12 2022" "Version 1.2" "Regions Of Interest (ROI) Profiler" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tests.unit.test_analyze
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBReportDirectoryTest\fP"
.br
.ti -1c
.RI "class \fBFilteringFlagsTest\fP"
.br
.ti -1c
.RI "class \fBSpy\fP"
.br
.ti -1c
.RI "class \fBRunAnalyzerTest\fP"
.br
.ti -1c
.RI "class \fBReportFailureTest\fP"
.br
.ti -1c
.RI "class \fBAnalyzerTest\fP"
.br
.ti -1c
.RI "class \fBRequireDecoratorTest\fP"
.br
.ti -1c
.RI "class \fBPrefixWithTest\fP"
.br
.ti -1c
.RI "class \fBMergeCtuMapTest\fP"
.br
.ti -1c
.RI "class \fBExtdefMapSrcToAstTest\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBmethod_without_expecteds\fP (opts)"
.br
.ti -1c
.RI "def \fBmethod_with_expecteds\fP (opts)"
.br
.ti -1c
.RI "def \fBmethod_exception_from_inside\fP (opts)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "def tests\&.unit\&.test_analyze\&.method_exception_from_inside ( opts)"

.PP
Definition at line 329 of file test_analyze\&.py\&.
.PP
.nf
329 def method_exception_from_inside(opts):
330     raise Exception('here is one')
331 
332 
.fi
.SS "def tests\&.unit\&.test_analyze\&.method_with_expecteds ( opts)"

.PP
Definition at line 324 of file test_analyze\&.py\&.
.PP
.nf
324 def method_with_expecteds(opts):
325     return 0
326 
327 
328 @sut\&.require([])
.fi
.PP
Referenced by tests\&.unit\&.test_analyze\&.RequireDecoratorTest\&.test_method_with_expecteds()\&.
.SS "def tests\&.unit\&.test_analyze\&.method_without_expecteds ( opts)"

.PP
Definition at line 319 of file test_analyze\&.py\&.
.PP
.nf
319 def method_without_expecteds(opts):
320     return 0
321 
322 
323 @sut\&.require(['this', 'that'])
.fi
.PP
Referenced by tests\&.unit\&.test_analyze\&.RequireDecoratorTest\&.test_method_without_expecteds()\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Regions Of Interest (ROI) Profiler from the source code\&.
